# Generated by Django 4.0.1 on 2022-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
    ]
