# Generated by Django 4.0.1 on 2022-02-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='VideoAnnotations',
        ),
    ]
