# Generated by Django 4.0.1 on 2022-02-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_rename_data_videoannotations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoannotations',
            unique_together={('type', 'pid')},
        ),
    ]
