# Generated by Django 4.0.1 on 2022-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_videoannotations_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoannotations',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoannotations',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
